let state = {
  drawer:false,
  scrollTop:0,
  blogInfo: null,
  searchFlag: false,
  loginFlag: false,
  registerFlag: false,
  forgetFlag: false,
  emailFlag: false,
  userId: null,
  avatar: null,
  nickname: null,
  intro: null,
  webSite: null,
  loginType: null,
  email: null,
  articleLikeSet: [],
  commentLikeSet: [],
  talkLikeSet: [],
}
export default state;
